//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyBalance
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIN_D6_pY_whU2XgVAADuhzxdw___0
    {
        public string ISBN { get; set; }
        public Nullable<byte> ID_AUT { get; set; }
    }
}
