//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyBalance
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIN_D6_pY_wUU2XgVAADuhzxdw___0
    {
        public short NUMERO { get; set; }
        public Nullable<System.DateTime> DATE_ACHAT { get; set; }
        public Nullable<decimal> PRIX { get; set; }
        public string CODE_PRET { get; set; }
        public string ETAT { get; set; }
        public string ISBN { get; set; }
    }
}
