//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyBalance
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIN_Eiu5KedaBhXgVAADuhzxdw___0
    {
        public string CAT_ID { get; set; }
        public string CAT_NAME { get; set; }
        public string CAT_DESCR { get; set; }
        public Nullable<System.DateTime> CAT_VALIDATIONDATE { get; set; }
        public string CAT_PARENT { get; set; }
    }
}
