//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyBalance
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIN_D6_pY_v3U2XgVAADuhzxdw___0
    {
        public int NUM_AB { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string VILLE { get; set; }
        public Nullable<byte> AGE { get; set; }
        public Nullable<short> TARIF { get; set; }
        public Nullable<byte> REDUC { get; set; }
        public Nullable<System.DateTime> DATE_NAI { get; set; }
        public string TYPE_AB { get; set; }
        public string CAT_AB { get; set; }
    }
}
