//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyBalance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTAINSACCESSORY
    {
        public string ROOM_ID { get; set; }
        public string ACCESSORY_ID { get; set; }
        public Nullable<decimal> CONTAINS_QUANTITY { get; set; }
    
        public virtual ACCESSORY ACCESSORY { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
