//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyBalance.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENT()
        {
            this.REPETITIVE_EVENT = new HashSet<REPETITIVE_EVENT>();
            this.USER1 = new HashSet<USER1>();
        }
    
        public string EVENT_ID { get; set; }
        public decimal EVENT_DURATION { get; set; }
        public string EVENT_NAME { get; set; }
        public decimal EVENT_PRICE { get; set; }
        public decimal EVENT_MAXNBR { get; set; }
        public string EVENT_ACTIVITY { get; set; }
        public string EVENT_ROOM { get; set; }
        public string EVENT_CONTRIBUTOR { get; set; }
        public string EVENT_MANAGER { get; set; }
        public string EVENT_TYPE { get; set; }
        public System.DateTime EVENT_DATE { get; set; }
    
        public virtual ACTIVITY ACTIVITY { get; set; }
        public virtual CONTRIBUTOR CONTRIBUTOR { get; set; }
        public virtual MANAGER MANAGER { get; set; }
        public virtual ROOM ROOM { get; set; }
        public virtual EVENTTYPE EVENTTYPE { get; set; }
        public virtual PUNCTUAL_EVENT PUNCTUAL_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPETITIVE_EVENT> REPETITIVE_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER1> USER1 { get; set; }
    }
}
