//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyBalance.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PURCHASE()
        {
            this.PURCHASECONTAINS = new HashSet<PURCHASECONTAINS>();
        }
    
        public string PURCHASE_ID { get; set; }
        public string PURCHASE_USERID { get; set; }
        public System.DateTime PURCHASE_DATE { get; set; }
        public Nullable<System.DateTime> PURCHASE_SHIPDATE { get; set; }
        public decimal PURCHASE_TOTALPRICE { get; set; }
    
        public virtual USER1 USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASECONTAINS> PURCHASECONTAINS { get; set; }
    }
}
