//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyBalance.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER1()
        {
            this.HASINBASKET = new HashSet<HASINBASKET>();
            this.NOTIFICATION = new HashSet<NOTIFICATION>();
            this.PRODUCT = new HashSet<PRODUCT>();
            this.PURCHASE = new HashSet<PURCHASE>();
            this.EVENT = new HashSet<EVENT>();
        }
    
        public string USER_ID { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_LASTNAME { get; set; }
        public string USER_FIRSTNAME { get; set; }
        public string USER_ADR1 { get; set; }
        public string USER_ADR2 { get; set; }
        public string USER_PC { get; set; }
        public string USER_TOWN { get; set; }
        public string USER_PHONE { get; set; }
        public string USER_MAIL { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual CONTRIBUTOR CONTRIBUTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HASINBASKET> HASINBASKET { get; set; }
        public virtual MANAGER MANAGER { get; set; }
        public virtual MEMBER MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION> NOTIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE> PURCHASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT> EVENT { get; set; }
    }
}
